#!/usr/bin/env python3
"""Regenerates ../Generated/CaseFoldingData.g.cs from the Unicode Character Database.

Two tables are produced, one per mode of ECMA-262 §22.2.2.9.4 Canonicalize:

* ``SimpleFold`` — the "common + simple" case folding of ``CaseFolding.txt``
  (status ``C`` and ``S``). This is exactly what Canonicalize returns when either
  Unicode flag is set and ``i`` is on.
* ``UpperFold`` — the non-Unicode branch, precomputed per UTF-16 code unit: the
  Default Case Conversion ``toUppercase`` of the single code unit, discarded when
  it is not a single code unit or when a non-ASCII input would fold into ASCII.
  ``toUppercase`` here is the unconditional ``SpecialCasing.txt`` mapping when one
  exists, otherwise the simple uppercase of ``UnicodeData.txt`` field 12.

Both are emitted as one string of comma-separated runs, ``lo[.hi]:[-]delta`` in
hexadecimal, where every code point in ``lo..hi`` canonicalizes to itself plus
``delta``. The inverse (fold orbit) map is rebuilt at run time, so it is not
emitted here.

Usage:

    base=https://www.unicode.org/Public/17.0.0/ucd
    for f in CaseFolding UnicodeData SpecialCasing; do curl -sO "$base/$f.txt"; done
    python generate-case-folding.py
    mv CaseFoldingData.g.cs ../Generated/
"""

import os
import sys

UNICODE_VERSION = "17.0.0"


def fields(line):
    line = line.split("#", 1)[0]
    if not line.strip():
        return None
    return [f.strip() for f in line.split(";")]


def read_case_folding(path):
    """code point -> simple/common case fold target."""
    fold = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            parts = fields(line)
            if not parts or len(parts) < 3:
                continue
            code, status, mapping = parts[0], parts[1], parts[2]
            if status not in ("C", "S"):
                continue
            targets = mapping.split()
            if len(targets) != 1:
                continue  # a C/S entry is single-valued by definition; be safe
            fold[int(code, 16)] = int(targets[0], 16)
    return fold


def read_simple_uppercase(path):
    """code point -> simple uppercase (UnicodeData.txt field 12), ranges included."""
    upper = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            parts = fields(line)
            if not parts or len(parts) < 13:
                continue
            if not parts[12]:
                continue
            upper[int(parts[0], 16)] = int(parts[12], 16)
    return upper


def read_unconditional_uppercase(path):
    """code point -> full uppercase, for the unconditional SpecialCasing.txt entries."""
    special = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            parts = fields(line)
            if not parts or len(parts) < 4:
                continue
            # A conditional entry carries a non-empty fifth field (the condition list);
            # Default Case Conversion uses the unconditional ones only.
            if len(parts) >= 5 and parts[4]:
                continue
            special[int(parts[0], 16)] = [int(c, 16) for c in parts[3].split()]
    return special


def build_upper_fold(simple_upper, special_upper):
    """The non-Unicode Canonicalize, precomputed for every UTF-16 code unit."""
    fold = {}
    for ch in range(0x10000):
        mapped = special_upper.get(ch)
        if mapped is None:
            single = simple_upper.get(ch)
            mapped = [single] if single is not None else [ch]
        if len(mapped) != 1:
            continue  # step 4: a multi-code-unit uppercasing leaves ch alone
        cu = mapped[0]
        if cu == ch:
            continue
        if ch >= 128 and cu < 128:
            continue  # step 6: a non-ASCII code unit never folds into ASCII
        fold[ch] = cu
    return fold


def encode(fold):
    """Packs a code-point -> code-point map into comma-separated `lo[.hi]:[-]delta` runs."""
    runs = []
    for code in sorted(fold):
        delta = fold[code] - code
        if runs and runs[-1][1] == code - 1 and runs[-1][2] == delta:
            runs[-1][1] = code
            continue
        runs.append([code, code, delta])

    parts = []
    for lo, hi, delta in runs:
        span = f"{lo:X}" if lo == hi else f"{lo:X}.{hi:X}"
        sign = "-" if delta < 0 else ""
        parts.append(f"{span}:{sign}{abs(delta):X}")
    return ",".join(parts)


def chunk(text, width=100):
    return [text[i:i + width] for i in range(0, len(text), width)]


def emit(simple, upper, out_path):
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            "// <auto-generated>\n"
            f"//     Generated from the Unicode Character Database {UNICODE_VERSION}\n"
            "//     by Unicode/tools/generate-case-folding.py. Do not edit by hand.\n"
            "// </auto-generated>\n"
            "\n"
            "namespace Broiler.Regex.Unicode;\n"
            "\n"
            "/// <summary>Generated case-fold tables for ECMA-262 §22.2.2.9.4 Canonicalize.</summary>\n"
            "internal static class CaseFoldingData\n"
            "{\n"
            f"    /// <summary>The Unicode revision these tables were generated from.</summary>\n"
            f"    public const string UnicodeVersion = \"{UNICODE_VERSION}\";\n"
            "\n"
            "    /// <summary>CaseFolding.txt \"common + simple\" folding — the u/v-mode branch.</summary>\n"
            "    public const string SimpleFold =\n"
        )
        write_string(handle, simple)
        handle.write(
            "\n"
            "    /// <summary>Per-code-unit toUppercase canonicalization — the non-Unicode branch.</summary>\n"
            "    public const string UpperFold =\n"
        )
        write_string(handle, upper)
        handle.write("}\n")


def write_string(handle, text):
    lines = chunk(text)
    for index, line in enumerate(lines):
        terminator = ";" if index == len(lines) - 1 else " +"
        handle.write(f"        \"{line}\"{terminator}\n")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    for name in ("CaseFolding.txt", "UnicodeData.txt", "SpecialCasing.txt"):
        if not os.path.exists(os.path.join(here, name)):
            sys.exit(f"missing {name}; see the module docstring for the download commands")

    simple = read_case_folding(os.path.join(here, "CaseFolding.txt"))
    simple_upper = read_simple_uppercase(os.path.join(here, "UnicodeData.txt"))
    special_upper = read_unconditional_uppercase(os.path.join(here, "SpecialCasing.txt"))
    upper = build_upper_fold(simple_upper, special_upper)

    out_path = os.path.join(here, "CaseFoldingData.g.cs")
    emit(encode(simple), encode(upper), out_path)
    print(f"{len(simple)} simple folds, {len(upper)} uppercase folds -> {out_path}")


if __name__ == "__main__":
    main()
